table ResponsibilityProfiles
	lineageTag: 9d749b60-fae7-43e0-9f4d-762595a59320

	/// Unique Globally Unique Id for the profile. Can be used to join to other entities that require resolving profile details, e.g. to UserStates.ResponsibilityProfileId
	column Id
		dataType: string
		lineageTag: ac596b63-adc1-47c4-80db-7805babc0d1d
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	/// Unique Id of the tenant where the profile was created
	column TenantId
		dataType: string
		lineageTag: 1581ce68-a8de-4d5f-81c4-1f5eb375789e
		summarizeBy: none
		sourceColumn: TenantId

		annotation SummarizationSetBy = Automatic

	/// Flag indicating whether the profile has been set as "on duty" or "off duty" when it was created.
	/// 
	/// This flag returns a value of true (1) when the profile was set as "On Duty".
	column IsDuty
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: df52e7c6-0178-4b0f-9e82-28402a9d078c
		summarizeBy: none
		sourceColumn: IsDuty

		annotation SummarizationSetBy = Automatic

	/// Unique Id of the Organization Unit of the profile
	column OrganizationUnitId
		dataType: string
		lineageTag: c7c6b059-5d3c-47fa-99f3-0b0146ebf6b7
		summarizeBy: none
		sourceColumn: OrganizationUnitId

		annotation SummarizationSetBy = Automatic

	/// Name of the profile as defined in Nimbus
	column 'Profile Name'
		dataType: string
		lineageTag: 49029689-726b-4da7-ac84-9febcfd0314b
		summarizeBy: none
		sourceColumn: Profile Name

		annotation SummarizationSetBy = Automatic

	partition ResponsibilityProfiles-d555d5e0-1f56-43c7-9bf7-ad957ba0e37a = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				                Source = GlobalSource,
				                RP_table = Source{[Name="ResponsibilityProfiles",Signature="table"]}[Data],
				                StopFolding = Table.StopFolding(RP_table),
				                #"Renamed Columns" = Table.RenameColumns(StopFolding, {{"Name", "Profile Name"}})
				              
				            in
				                #"Renamed Columns"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

